FROM python:3.12.2-slim

# TODO: these images are really big...
# Do something to slim them down

WORKDIR /app
COPY reqs.txt .
RUN python3 -m pip install --upgrade pip && python3 -m pip install flask gunicorn && python3 -m pip install --no-cache-dir -r reqs.txt --extra-index-url https://download.pytorch.org/whl/cpu && python3 -m pip cache purge

COPY *.py ./
COPY *.pth ./
COPY imagenet_classes.txt ./

ENTRYPOINT [ "gunicorn", "-w", "1", "server:app" ]